S3 dynamisation
WildCodeSchool/orleans-0217-myorleans pull request #12
Opened 2017-06-26 14:41 UTC by WCSIsabelle

@open-it @sblondeau : les fonctionnalites de recherche simple et recherche avancée sont fonctionnelles. 
Il faut optimiser le code dans NosBiensController pour enlever les choses annexes codées en dur (message, objectif, notamment) --> next step :)

2017-06-26 15:28 UTC, open-it commented on app/config/config.yml
>          address: wildersmyorleans@gmail.com #"%mailer_user%"
Pourquoi avoir retiré les paramètres ?

2017-06-26 15:35 UTC, open-it commented on src/MyOrleansBundle/Controller/front/BlogController.php
> +        $tag = $nomTag[0];
Pourquoi parcourir tous les tags pour finalement ne prendre que le 1er ?

2017-06-26 15:36 UTC, open-it commented on src/MyOrleansBundle/Controller/front/HomeController.php
> +        // TMP
on ne push pas du code "TMP"

2017-06-27 07:53 UTC, open-it requested changes
2 ou 3 petites remarques à corriger ;)

2017-06-27 09:48 UTC, WCSIsabelle commented
1. Les paramètres dans config.yml ont été remis.
2. J'ai simplifié la recherche par Tag -->sélection du premier tag tout de suite :)
3. La partie relative à immo pratique (code TMP), JB travaille dessus en ce moment, ce sera clean qd il fera sa pull request.

4. J'ai aussi modifié l'affichage dynamique de l'encart residence sur la page article blog --> je me sers de VignetteResidenceController, comme pour la page NosBiens.

Si tu veux rejeter un coup d'oeil !

2017-06-27 12:40 UTC, sblondeau requested changes
quelques petites choses pas très claires, à préciser

2017-06-27 12:40 UTC, sblondeau commented on src/MyOrleansBundle/Controller/VignetteResidenceController.php
> +    public function affichageResidenceAction($id, $param, CalculateurCaracteristiquesResidence $calculateur)
pas utiliser $id mais le paraconverter

2017-06-27 12:40 UTC, sblondeau commented on src/MyOrleansBundle/Controller/VignetteResidenceController.php
>          $typeMax = $typeMinMax[1];
c'est quoi ce typeMinMax[0] et [1]

2017-06-27 12:40 UTC, sblondeau commented on src/MyOrleansBundle/Controller/VignetteResidenceController.php
> +        } else {
obligatoire ce $param ? je vois pas trop l'intéret d'avoir deux render différent qui affichent les memes choses ? y a surement moyen de faire plus simple avec des render coté twig non ?

2017-06-27 12:40 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/affichage_residence.html.twig
> +            <a href="{{ path('residences', { 'idResidence': residence.id }) }}">Découvrir la résidence</a>
pourquoi idResidence et non id ?

2017-06-27 12:40 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/blog/blog_affichage_residence.html.twig
> +        <a href="{{ path('residences', { 'idResidence': residence.id }) }}">Découvrir la résidence</a>
pareil

2017-06-27 14:35 UTC, WCSIsabelle commented
1. Utlisation param converter OK
2. Modifs idResidence et idArticle
3. Ajout d'une seconde méthode dans VignetteController

2017-06-27 21:52 UTC, sblondeau approved these changes

2017-06-27 22:34 UTC, sblondeau commented
je vous laisse faire la correction des conflits, il y a une explication de la procédure si tu cliques sur "Use the command line" si vous avez des doutes ...

2017-06-28 09:24 UTC, open-it approved these changes

2017-06-28 09:33 UTC, WCSIsabelle commented
@open-it : Hallelujah plus de conflits ! :)

2017-06-28 09:34 UTC, merged