Notation
WildCodeSchool/orleans-0217-myorleans pull request #16
Opened 2017-06-27 09:40 UTC by Solcain

coucou nico

2017-06-27 14:38 UTC, Solcain commented
@open-it 
@sblondeau

2017-06-27 22:11 UTC, sblondeau requested changes

2017-06-27 22:11 UTC, sblondeau commented on app/config/config.yml
> +        binary:     %kernel.root_dir%/../bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
%kernel.root_dir est déprécié avec la 3.3, utiliser plutot %kernel.project_dir (et je crois que tu n'as plus besoin des ../ dans ce cas mais à retester)

2017-06-27 22:11 UTC, sblondeau commented on app/config/config.yml
> +        binary:     %kernel.root_dir%/../bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
idem

2017-06-27 22:11 UTC, sblondeau commented on src/MyOrleansBundle/Controller/admin/FlatController.php
> +    public function pdfAction($id)
c'est un $id de Flat? Utiliser le paramConverter !

2017-06-27 22:11 UTC, sblondeau commented on src/MyOrleansBundle/Entity/Article.php~
>      /**
déversionner tous les fichier finissant par ~ (voit avec Isabelle elle l'a fait)

2017-06-27 22:11 UTC, sblondeau commented on src/MyOrleansBundle/Entity/CategoriePresta.php
> +    public function addTypePresta(\MyOrleansBundle\Entity\TypePresta $typePresta)
Prestation aurait du etre utlisé à la place de l'abbreviation Presta. Mais bon, je ne vais pas vous faire reprendre toutes vos variables maintenant il y aurait trop de boulot, aussi sur l'aspect anglais/français...

2017-06-27 22:11 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/residence.html.twig
>      <link rel="stylesheet" href="{{ asset('css/stylesheet.css') }}" media="screen,projection"/>
ces feuilles de style ne devraient pas etre justement dans le layout ou le base ?

2017-06-27 22:11 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/residence.html.twig
> +                            <div class="notesite" id="note_0" data-note="9.30"></div><br/>
les notes sont en dur dans le code ? pas encore rendu dynamique ? si oui, ça ne devrait pas etre dans la PR... à rendre dynamique !

2017-06-27 22:11 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/residence.html.twig
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
jquery ne devrait pas etre chargé depuis un site externe
Jquery devrait etre appelé dans base.html (car utilisé partout), si c'est le cas, le {{parent()}} l'appelle et il est donc réapeller une seconde fois ici... à revoir le fonctionnement des block stylesheets et javascripts !

2017-06-27 22:11 UTC, sblondeau commented on web/css/residence.css
> +    -webkit-transform: rotate(180deg) !important;
pas de !important !!!

2017-06-28 09:35 UTC, Solcain commented on src/MyOrleansBundle/Resources/views/residence.html.twig
> +                            <div class="notesite" id="note_0" data-note="9.30"></div><br/>
j'ai une autre branche pour tout rendre dynamique

2017-06-28 09:44 UTC, Solcain commented on web/css/residence.css
> +    -webkit-transform: rotate(180deg) !important;
ça c'est pa moi c'est le code source que j'ai repris du site existant et si je ne met pas !important ça ne marche pas ...

2017-06-28 09:47 UTC, Solcain commented
@open-it 
@sblondeau

2017-06-28 12:11 UTC, sblondeau commented on web/css/residence.css
> +    -webkit-transform: rotate(180deg) !important;
ok mais j'aime pas. Tu devrais être capable de faire sans ;-) c'est tu as quoi ça sert le !important ? et du coup comment t'en passer ?

2017-06-28 15:08 UTC, sblondeau approved these changes

2017-06-28 15:56 UTC, merged