ajout formulaire de contact fonctionnel
WildCodeSchool/orleans-0217-myorleans pull request #19
Opened 2017-06-30 09:56 UTC by jbh225

ajout formulaire de contact sur page nos-services, immopratique et page d'accueil
@sblondeau

2017-06-30 10:37 UTC, sblondeau requested changes
deversionner les fichiers ~

2017-06-30 10:37 UTC, sblondeau commented on .gitignore
>  >>>>>>> 8ddd01b11fbe0d8f81868096f5b9e58d8350b48a
bout de conflit mal réglé

2017-06-30 10:37 UTC, sblondeau commented on .gitignore
> +!/src/MyOrleansBundle/Resources/views/receptionform.html.twig
c'est quoi cette page ?

2017-06-30 10:37 UTC, sblondeau commented on src/MyOrleansBundle/Entity/Article.php~
>   */
à déversionner !!!

2017-07-02 20:38 UTC, sblondeau requested changes

2017-07-02 20:38 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/HomeController.php
> +                ->setTo('wildersmyorleans@gmail.com')
non! les mails, clés et autres sont à mettre dans le fichiers parameters.yml, on l'a déjà répéter plein de fois !

2017-07-02 20:38 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/NosServicesController.php
> +                ->setTo('wildersmyorleans@gmail.com')
idem

2017-07-03 09:32 UTC, jbh225 commented on .gitignore
> +!/src/MyOrleansBundle/Resources/views/receptionform.html.twig
J'ai supprimé. Je sais pas pourquoi elle s'est affichée ici

2017-07-03 09:32 UTC, jbh225 commented on src/MyOrleansBundle/Entity/Article.php~
>   */
fait

2017-07-03 11:14 UTC, sblondeau requested changes

2017-07-03 11:14 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/ClientController.php
> +            return $this->redirectToRoute('nosservices');
devrait s'appeler nos_services (mots séparés par des underscores)

2017-07-03 11:14 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/ClientController.php
> +        return $this->render('MyOrleansBundle::nosservices.html.twig', array('form' => $form->createView()));
pb de nommage, devrait etre nosServices.html.twig ou nos_services.html.twig (selon une convention que vous choisissez en début de projet)

2017-07-03 11:14 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/HomeController.php
> +                        array('client' => $client)
tu devrais utiliser la syntaxe [] plutot que array

2017-07-03 11:14 UTC, sblondeau commented on src/MyOrleansBundle/Entity/Client.php
> +     * @ORM\Column(name="telephone", type="integer", length=10, nullable=true)
pensez à faire des Assets sur vos entities (validation)

2017-07-03 11:14 UTC, sblondeau commented on src/MyOrleansBundle/Form/FormulaireType.php
> +                'choices' => array('oui' => true, 'non' => false),
syntaxe [] plutot qu'array

2017-07-03 11:14 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/immopratique.html.twig
> +        <img src="{{ asset('img/orleans2.jpg') }}" style="width: 100%; margin-bottom: -90px;"
pas de style en atttribut

2017-07-03 11:14 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/immopratique.html.twig
> +                        <p style="text-align: center">Je souhaite m'abonner à la newsletter?</p>
pas de style !

2017-07-03 11:14 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                {#<div id="modal1" class="modal modal-fixed-footer">
enlever le code commenté !

2017-07-03 11:14 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                <h4 align="center">02.38.75.94.47</h4>
le num de téléphone ne doit pas etre en dur, soit c'est stocké en base, soit c'est au minimum en paramètre (comme pour les mails)

2017-07-03 16:15 UTC, sblondeau approved these changes

2017-07-04 10:09 UTC, merged