Upload avec collectionType
WildCodeSchool/orleans-0217-myorleans pull request #26
Opened 2017-07-04 12:49 UTC by HageraN

Upload de médias sur les entités : collaborateur, partenaire, pack, service, résidence, flat, evenement, articles.

@sblondeau

2017-07-04 13:39 UTC, sblondeau requested changes
de plus, les images uploadées ne doivent pas etre versionnées !

2017-07-04 13:39 UTC, sblondeau commented on src/MyOrleansBundle/Controller/admin/ArticleController.php
> +                $file = $media->getLien();
pourquoi du code d'upload dans le controlleur alors que tu as des eventlistener et un service ?

2017-07-04 13:39 UTC, sblondeau commented on src/MyOrleansBundle/Controller/admin/ArticleController.php
> +                    $filename = $fileUploader->upload($file);
pareil là, je ne te le mets pas partout ailleurs

2017-07-04 13:39 UTC, sblondeau commented on src/MyOrleansBundle/Entity/Prestation.php~
> +<?php
a déversionner d#*s&df!dif* !!!

2017-07-04 13:39 UTC, sblondeau commented on src/MyOrleansBundle/Form/ArticleType.php
> +                /*'allow_delete' => true,
code commenté

2017-07-04 13:39 UTC, sblondeau commented on src/MyOrleansBundle/Form/TagType.php
> +           // ->add('articles', CollectionType::class);
code commenté

2017-07-04 21:32 UTC, sblondeau requested changes

2017-07-04 21:32 UTC, sblondeau commented on app/Resources/views/residence/edit.html.twig
> +{% block javascripts %}
j'ai l'impression que tu répètes plein de fois le meme code js dans plein de méthodes, tu ne peux pas déporter ça dans un fichier externe ?

2017-07-04 21:32 UTC, sblondeau commented on src/MyOrleansBundle/Controller/admin/ArticleController.php
> +    public function deleteMedia(Article $article, Media $media)
devrait s'appeler deleteMediaAction

2017-07-04 21:32 UTC, sblondeau commented on src/MyOrleansBundle/Controller/admin/CollaborateurController.php
> +    public function deleteMedia(Collaborateur $collaborateur)
deleteMediaAction

2017-07-04 21:32 UTC, sblondeau commented on src/MyOrleansBundle/Controller/admin/EvenementController.php
> +    public function deleteMedia(Media $media)
idem (et partout ailleurs)

2017-07-05 13:34 UTC, HageraN commented
@sblondeau J'ai effectué les corrections nécessaires :) !

2017-07-05 14:33 UTC, sblondeau requested changes
upload ne doit pas etre versionné
pareil c'est quoi web/cache ?

2017-07-05 15:35 UTC, sblondeau approved these changes

2017-07-05 15:35 UTC, merged