ajout message flash pour formulaire + nouveau champ select
WildCodeSchool/orleans-0217-myorleans pull request #28
Opened 2017-07-05 13:52 UTC by jbh225

2017-07-05 15:34 UTC, sblondeau requested changes
- déversionner /web/media
- faire des PR beaucoup plus petites, là je suis surement passé à coté de plein de chose... là prochaine fois que tu m'en envoies une si grosse je la refuse sans même la lire !
- beaucoup d'erreurs qui ne devraient pas être présentes, relit (ou fait relire) avant de pusher

2017-07-05 15:34 UTC, sblondeau commented on app/Resources/FOSUserBundle/views/layout.html.twig
> +                         height="80px"/><br>
pas de height

2017-07-05 15:34 UTC, sblondeau commented on app/Resources/views/evenement/index.html.twig
> +<<<<<<< HEAD
bout de code de merge mal retirer, faire vraiment attention à ca !!!

2017-07-05 15:34 UTC, sblondeau commented on app/Resources/views/evenement/index.html.twig
> +                <td>{% if evenement.dateDebut %}{{ evenement.dateDebut|date('Y-m-d') }}{% endif %}</td>
tu devrais pouvoir faire
<td>{{ evenement.dateDebut|default('') }}</td>
ou même plus court
<td>{{ evenement.dateDebut ?? '' }}</td>
ça signifie si evement.dateDebut n'existe pas, utilise la valeur par défaut (ici chaine vide)

2017-07-05 15:34 UTC, sblondeau commented on app/Resources/views/evenement/index.html.twig
> +=======
bout de code merge restant

2017-07-05 15:34 UTC, sblondeau commented on app/Resources/views/evenement/index.html.twig
> +>>>>>>> baf4400a67b4f134288fe5b5c2d9bbfffba23d19
idem

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/HomeController.php
> +        $client = new  Client();
tu as 3 espaces entre new et Client()
c'est un détail mais qui ne devrait pas apparaître car tu devrais faire un ctrl+alt+L ds phpstorm avant chaque commit pour être compatible PSR !

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/HomeController.php
>          if (isset($_SESSION)) {
pas de $_SESSION !!!!!!!!!

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Form/FormulaireType.php
> +                'choices' => array('Objet ?' => 0, 'Residence principale' => 1, 'Investissement' => 2, 'Services' => 3),
tu ne devrais pas mettre d'Objets=>?
tu as des option dans le choiceType (empty_data de mémoire) pour gérer ça

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Form/FormulaireType.php
> +                'choices' => array('Objet ?' => 0, 'Residence principale' => 1, 'Investissement' => 2, 'Services' => 3),
et tu devrais utiliser la syntaxe [] partout au lieu de array (en tout cas pas les deux mélangées)

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/agence.html.twig
>              {{ parent() }}
le parent doit etre applé avant les fichiers js car plus génériques

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/index.html.twig
>                          {% elseif parcours == null %}
ce elseif ne sert à rien

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                            <li>
tu as parcours qui prend comme valeur investisseur ou residence ou null
tu peux donc faire plutot: 
```
{% if parcours %}
  <li>
  <div class="icone-profil icone-{{parcours}}">
<a href={{path('parcours', {(profil': parcours, route... >
... 
```

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                        {#<li><a href="{{ path("parcoursimmo") }}">Parcours immobiliers</a></li>#}
code commenté

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                        {#<li><a href="{{ path("parcoursimmo") }}">Parcours immobiliers</a></li>#}
code commenté

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                    <h3>"Nous sommes passionnés par l’immobilier et par les relations avec nos partenaires et nos
un texte si long devrait etre un <p> non un titre

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                                    <br><span>{{ collaborateur.fonction }}</span></p>
déja on écrit <br/> et non <br> et on ne l'utilise pas poru de la mise en page !

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/nosServices.html.twig
> +            {% elseif service.id is even %}
un else suffit, si c'est pas pair s'est forcément impair !

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/receptionForm.html.twig
> +    {% if client.sujet == 1 %}
la partie du code `<p><strong>Sujet</strong>: `
ne devrait pas être répétée à chaque fois, juste le contenu qui change

2017-07-05 15:34 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/receptionForm.html.twig
> +        <p><strong>Inscription newsletter</strong>: non </p>
pareil ici

2017-07-05 16:47 UTC, jbh225 commented on app/Resources/FOSUserBundle/views/layout.html.twig
> +                         height="80px"/><br>
fait

2017-07-05 16:47 UTC, jbh225 commented on app/Resources/views/evenement/index.html.twig
> +<<<<<<< HEAD
supprimé

2017-07-05 16:47 UTC, jbh225 commented on app/Resources/views/evenement/index.html.twig
> +                <td>{% if evenement.dateDebut %}{{ evenement.dateDebut|date('Y-m-d') }}{% endif %}</td>
fait

2017-07-05 16:47 UTC, jbh225 commented on app/Resources/views/evenement/index.html.twig
> +=======
fait

2017-07-05 16:48 UTC, jbh225 commented on app/Resources/views/evenement/index.html.twig
> +>>>>>>> baf4400a67b4f134288fe5b5c2d9bbfffba23d19
fait

2017-07-05 16:48 UTC, jbh225 commented on src/MyOrleansBundle/Controller/front/HomeController.php
> +        $client = new  Client();
fait

2017-07-05 16:48 UTC, jbh225 commented on src/MyOrleansBundle/Form/FormulaireType.php
> +                'choices' => array('Objet ?' => 0, 'Residence principale' => 1, 'Investissement' => 2, 'Services' => 3),
fait

2017-07-05 16:49 UTC, jbh225 commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                            <li>
merci mais la version initiale est beaucoup plus comprehensible

2017-07-05 16:49 UTC, jbh225 commented on src/MyOrleansBundle/Resources/views/index.html.twig
>                          {% elseif parcours == null %}
fait

2017-07-05 16:49 UTC, jbh225 commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                    <h3>"Nous sommes passionnés par l’immobilier et par les relations avec nos partenaires et nos
fait

2017-07-05 16:49 UTC, jbh225 commented on src/MyOrleansBundle/Resources/views/nosServices.html.twig
> +            {% elseif service.id is even %}
fait

2017-07-05 21:45 UTC, jbh225 commented
j'ai fait une pull request sur master, je me suis trompé! je voulais faire de dev a jbhmessage

2017-07-06 07:10 UTC, sblondeau requested changes

2017-07-06 07:10 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/receptionForm.html.twig
> +    {% if client.sujet == 1 %}
je ne t'ai pas dis de virer les strong, juste de mutualiser le bout de code `<p>Sujet:` que tu répètes 4 fois et qui pourrais être sorti de la condition

2017-07-06 10:08 UTC, jbh225 commented on src/MyOrleansBundle/Resources/views/receptionForm.html.twig
> +    {% if client.sujet == 1 %}
c'est bon @sblondeau j'ai modifié !

2017-07-06 10:20 UTC, sblondeau approved these changes

2017-07-06 10:20 UTC, sblondeau commented on src/MyOrleansBundle/Form/FormulaireType.php
> +                'choices' => ['Objet du message?'=> null, 'Residence principale' => 1, 'Investissement' => 2, 'Services' => 3],
non, du coup il faudrait virer Objet du messge des choices. Le champ est-il obligatoire ? ça change des choses

2017-07-06 10:20 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/receptionForm.html.twig
> +        <p><strong>:
voila !

2017-07-06 10:20 UTC, merged