Tags - CollectionType
WildCodeSchool/orleans-0217-myorleans pull request #33
Opened 2017-07-06 16:08 UTC by HageraN

Ajout de tags dans la page Article de l'espace administrateur
@sblondeau

2017-07-06 21:11 UTC, sblondeau requested changes

2017-07-06 21:11 UTC, sblondeau commented on app/Resources/views/article/new.html.twig
> +                            {# {{ form_start(form) }}
code commenté

2017-07-07 07:04 UTC, HageraN commented on app/Resources/views/article/new.html.twig
> +                            {# {{ form_start(form) }}
@sblondeau J'ai supprimé le code commenté

2017-07-07 07:09 UTC, sblondeau approved these changes

2017-07-07 07:09 UTC, merged