ajout bouton de partage reseaux sociaux et envoyez a un ami par mail
WildCodeSchool/orleans-0217-myorleans pull request #39
Opened 2017-07-07 09:20 UTC by jbh225

@sblondeau 

concerne page residences, appartement  et article de blog

2017-07-07 09:39 UTC, sblondeau requested changes

2017-07-07 09:39 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                <a class="waves-effect waves-light btn" href="mailto:?to=adresse1@serveur.com%2C%20adresse2@serveur.com &cc=adresseCopie@serveur.com &subject=Sujet%20du%20message">Envoyez à un ami pa
c'est quoi ça aussi avec des email en dur

2017-07-07 09:39 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                <div class="fb-share-button" data-href="http://localhost:8000/residences" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_bl
y a un pb avec ton bouton fa****ook, c'est quoi ce localhost:8000 en dur ? ça n'a pas de sens

2017-07-07 09:39 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/blog/blog_article.html.twig
> +                   href="https://twitter.com/intent/tweet?text=Hello%20world"
le param text Hello world n'est-il pas à modifier ?

2017-07-07 09:39 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/blog/blog_article.html.twig
> +                <div class="fb-share-button" data-href="http://localhost:8000/residences" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_bl
idem localhost 8000

2017-07-07 09:39 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/blog/blog_article.html.twig
> +                <a class="waves-effect waves-light btn" href="mailto:?to=adresse1@serveur.com%2C%20adresse2@serveur.com &cc=adresseCopie@serveur.com &subject=Sujet%20du%20message">Envoyez à un ami pa
idem

2017-07-07 09:39 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/layout.html.twig
> +        //partage facebook
si c'est le meme script que sur layout, soit tu le mets dans base si tu en as besoin partout, soit tu le mets dans un fichier js que tu appelles sur les 2 pages, parce que là ça fait un long code qui vient polluer tes fichiers layout

2017-07-07 09:39 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/residence.html.twig
> +               href="https://twitter.com/intent/tweet?text=Hello%20world"
idem

2017-07-07 09:39 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/residence.html.twig
> +            <div class="fb-share-button" data-href="http://localhost:8000/residences" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank"
idem

2017-07-07 09:39 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/residence.html.twig
> +            <a class="waves-effect waves-light btn" href="mailto:?to=adresse1@serveur.com%2C%20adresse2@serveur.com &cc=adresseCopie@serveur.com &subject=Sujet%20du%20message">Envoyez à un ami par ma
idem

2017-07-07 09:39 UTC, sblondeau commented on app/Resources/views/base.html.twig
> +        $('#alert_close').click(function () {
ca sert à quoi ce code js dans le base ?

2017-07-07 10:11 UTC, jbh225 commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                <div class="fb-share-button" data-href="http://localhost:8000/residences" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_bl
c'est le lien de la page, j'aurais pu mettre data-href="http://localhost:8000/residences{{residence.id}}" mais la page n'est pas encore responsive

2017-07-07 10:15 UTC, jbh225 commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                <a class="waves-effect waves-light btn" href="mailto:?to=adresse1@serveur.com%2C%20adresse2@serveur.com &cc=adresseCopie@serveur.com &subject=Sujet%20du%20message">Envoyez à un ami pa
c'est supprimé

2017-07-07 10:18 UTC, jbh225 commented on app/Resources/views/base.html.twig
> +        $('#alert_close').click(function () {
il ne sert plus apparamment, je l'ai supprimé

2017-07-07 10:20 UTC, jbh225 commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                <div class="fb-share-button" data-href="http://localhost:8000/residences" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_bl
c'était un tes, c'est le script qu'il te donne quand tu vas sur https://developers.facebook.com/docs/plugins/share-button?locale=fr_FR#

2017-07-07 11:51 UTC, sblondeau requested changes

2017-07-07 11:51 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                <div class="fb-share-button" data-href="http://localhost:8000/residences" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_bl
non mais tu ne dois pas mettre un "localhost" en dur dans ton code, ça ne va pas du tout. Tu dois générer un chemin dynamiquement par rapport à une route... avec un path()

2017-07-07 12:18 UTC, jbh225 commented
c'est modifié @sblondeau

2017-07-07 12:38 UTC, sblondeau requested changes

2017-07-07 12:38 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/blog/blog_article.html.twig
> +                    <div class="fb-share-button" data- href="{{ path('blog-article', { 'id': article.id }) }}" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-pars
il reste encore des localhost8000 ici...

2017-07-07 12:38 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/blog/blog_article.html.twig
> +                    <div class="fb-share-button" data- href="{{ path('blog-article', { 'id': article.id }) }}" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-pars
et à 2-3 autres endoits, je t'indique pas tout

2017-07-07 16:04 UTC, jbh225 commented
corrections faites ! @sblondeau

2017-07-09 21:19 UTC, sblondeau requested changes

2017-07-09 21:19 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                <div class="fb-share-button" data-href="{{ absolute_url( path('appartement', { 'id': appartement.id }))|url_encode }}" data-layout="button" data-size="large" data-mobile-iframe="true"
non ! tjs pas
le {{ absolute_url( path('appartement', { 'id': appartement.id }))|url_encode }} est à mettre dans le href, dans le data-href c'est la meme chose mais sans l'urlencode

2017-07-09 21:19 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/residence.html.twig
> +            <div class="fb-share-button" data-href="{{ absolute_url( path('residences', { 'id': residences.id }))|url_encode }}" data-layout="button" data-size="large" data-mobile-iframe="true"><a cl
idem

2017-07-10 06:00 UTC, jbh225 commented
modifications faites ! @sblondeau

2017-07-10 07:59 UTC, sblondeau requested changes

2017-07-10 07:59 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                <div class="fb-share-button" data-href="{{ absolute_url( path('appartement', { 'id': appartement.id }))|url_encode }}" data-layout="button" data-size="large" data-mobile-iframe="true"
il en reste un là d'url_encode à virer dans le data-href

2017-07-10 08:09 UTC, jbh225 commented
bon là je pense que c'est bon hein @sblondeau !

2017-07-10 09:38 UTC, sblondeau approved these changes

2017-07-10 10:00 UTC, merged