Pdf
WildCodeSchool/orleans-0217-myorleans pull request #42
Opened 2017-07-07 14:28 UTC by Solcain

@sblondeau

2017-07-09 21:29 UTC, sblondeau requested changes
beaucoup de choses à revoir
essaie de faire des PR plus petites à l'avenir

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/FlatController.php
> +        /*        $prestas = $em->getRepository(Presta::class)->findAll();
code commenté

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/FlatController.php
> +                /*            'prestas'=>$prestas,
code commenté

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/ResidencesController.php
> +/*        $prestas = $em->getRepository(Prestation::class)->findAll();
idem

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/ResidencesController.php
> +/*            'flats' => $flats,*/
encore !

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                        <span>Le Pryvé - Ref PRY13 - Type2</span>
c'est quoi cette ref en dur ?! ça doit etre dymamique

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
>                  <img src="{{ asset('img/apt-neuf.jpg') }}" class="photo-apt" alt="photo-appart"/>
pareil pour les images, il faut rendre la page dynamique

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +    <div class="container-fluid">
pareil pour tout ce qui suis, du dynamique, ça ne va pas du tout comme ça

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +        {#        <script>
code commenté

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/pdf_appartement.html.twig
> +    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
pas de cdn

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/pdf_appartement.html.twig
> +                    <span>Le Pryvé - Appartement Ref PRY13 - Type2</span>
idem, tout est en dur, pourquoi ce n'est pas dynamique, vous avez tout pour le faire normalement ?

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/pdf_residence.html.twig
> +    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
pareil CDN et infos en dur

2017-07-09 21:29 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/residence.html.twig
> +                                <td><strong>Prix</strong><br/><span class="subtab-residence"><strong>à partir de 90 000 €</strong></span>
données en dur encore une fois

2017-07-09 21:29 UTC, sblondeau commented on web/css/pdf.css
> +/*.content-residence{
code commenté

2017-07-09 21:29 UTC, sblondeau commented on web/css/pdf.css
> +/* --------------------------------------------------------------------*/
les commentaires c'est bien, mais juste un 
/***** PAGE APPARTEMENT ****/ ça suffit, pas la peine de 8 lignes ;-)

2017-07-09 21:29 UTC, sblondeau commented on web/css/pdf.css
> +html, body {
fichier très long
ne peux tu pas plutot reprendre le fichier css de base pour le reste du site (j'imagine que la mise en page est similaire entre le pdf et le site) et ajouter un pdf.css juste pour ce qui est différent, sinon ce n'est pas trop DRY

2017-07-10 07:50 UTC, Solcain commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +                        <span>Le Pryvé - Ref PRY13 - Type2</span>
J'ai une autre branche ou je suis en train de rendre tout dynamique, qui sera ma prochaine Pull Request

2017-07-10 08:24 UTC, Solcain commented on web/css/pdf.css
> +html, body {
le css du pdf n'a rien à voir car pas besoin de responsive et la disposition n'a rien à voir avec la page du site, je vais tout de meme voir à alléger le pdf.css

2017-07-10 14:50 UTC, sblondeau approved these changes
bon ... j'attends tes corrections sur les données "en dur" au plus vite

2017-07-10 15:15 UTC, merged