S7 suggestion biens
WildCodeSchool/orleans-0217-myorleans pull request #44
Opened 2017-07-10 12:28 UTC by WCSIsabelle

@sblondeau

2017-07-10 13:56 UTC, sblondeau requested changes

2017-07-10 13:56 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/NosBiensController.php
>              $article = $em->getRepository(Article::class)->articleByTag($tag, 1);
je pense que c'est équivalent à un findBy(['tag'=>$tag], ['id'=>'DESC'], 1, 0)  ?

2017-07-10 13:56 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/NosBiensController.php
>                  $article = $em->getRepository(Article::class)->articleByTag('Residence Principale', 1);
pareil ici

2017-07-10 13:56 UTC, sblondeau commented on src/MyOrleansBundle/Controller/front/NosBiensController.php
>              $residences = $em->getRepository(Residence::class)->completeSearch($ville, $quartier, $type, $surfaceMin,
ca aurait peut etre été plus simple de passer $data en paramètre et de faire les tests si null ou non dans les qb ?

2017-07-11 08:33 UTC, WCSIsabelle commented
@sblondeau : la simplification de la génération d'article par tag proposé ne fonctionne pas, j'ai laissé tel quel. Les changements au niveau du repository residence pour la recherche de biens à suggérer fonctionne ce matin!

2017-07-11 08:57 UTC, open-it approved these changes

2017-07-11 08:57 UTC, merged