S8 : affichage conditionnel du prix des appartements
WildCodeSchool/orleans-0217-myorleans pull request #46
Opened 2017-07-10 14:19 UTC by WCSIsabelle

…s backOfffice OK, affichage conditionnel du prix dans les vues du site OK

2017-07-10 14:40 UTC, sblondeau requested changes

2017-07-10 14:40 UTC, sblondeau commented on app/Resources/views/residence/edit.html.twig
> +                            <br/>
pas de <br/> pour de la mise en page, tu fais un <div> autour de ton block de form

2017-07-10 14:40 UTC, sblondeau commented on src/MyOrleansBundle/Form/ResidenceType.php
> +                    'Oui' => '1',
true et false plutot que 1 et 0 (et si tu devais vraiment mettre 0 et 1, pas entre quotes)

2017-07-10 14:40 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/affichage_residence.html.twig
> +                    {% if residence.affichagePrix == 1 %}
{% if residence.affichagePrix %} devrait suffire du coup

2017-07-11 09:03 UTC, WCSIsabelle commented
@sblondeau : modif effectuées

2017-07-11 09:07 UTC, open-it approved these changes

2017-07-11 09:07 UTC, merged