Vuedynanico
WildCodeSchool/orleans-0217-myorleans pull request #66
Opened 2017-07-11 15:17 UTC by Solcain

@open-it 
@sblondeau

2017-07-11 15:42 UTC, open-it commented on src/MyOrleansBundle/Controller/front/PdfController.php
> +    public function pdfFlatAction($id, Flat $flat, SessionInterface $session, Request $request, CalculateurCaracteristiquesResidence $calculateur)
A priori il y a un soucis ? A quoi correspond $id ??? $flat ne sert à rien... Plus loin dans le code tu fais toujours ton findAll sur les Flats etc etc...

2017-07-11 15:42 UTC, open-it commented on src/MyOrleansBundle/Controller/front/PdfController.php
> +    public function pdfResidenceAction($id,Residence $residence, SessionInterface $session, CalculateurCaracteristiquesResidence $calculateur)
Même remarque qu'au dessus.

2017-07-11 15:43 UTC, open-it commented on src/MyOrleansBundle/Controller/front/ResidencesController.php
>          $media = $em->getRepository(Media::class)->find($id);
$id ne peut pas être l'id de la residence ET du media en même temps. Pkoi un findAll sur les residences ?

2017-07-11 15:43 UTC, open-it commented on src/MyOrleansBundle/Entity/Prestation.php~
> +<?php
Ce fichier ne devrait pas être présent sur le repo !!!!!!

2017-07-11 15:44 UTC, open-it commented on src/MyOrleansBundle/Entity/Quartier.php~
> +<?php
IDEM

2017-07-11 15:44 UTC, open-it commented on src/MyOrleansBundle/Entity/Temoignage.php~
> +<?php
Pas de backup !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2017-07-11 15:44 UTC, open-it commented on src/MyOrleansBundle/Entity/TypeArticle.php~
> +<?php
Encore un...

2017-07-11 15:45 UTC, open-it commented on src/MyOrleansBundle/Entity/TypeLogement.php~
> +<?php
sans commentaire...

2017-07-11 15:45 UTC, open-it commented on src/MyOrleansBundle/Entity/TypeMedia.php~
> +<?php
...

2017-07-11 15:45 UTC, open-it commented on src/MyOrleansBundle/Entity/Ville.php~
> +<?php
...

2017-07-11 15:46 UTC, open-it commented on src/MyOrleansBundle/Repository/FlatRepository.php
> +    public function searchById($id)
Pourquoi une methode vide ?

2017-07-11 15:46 UTC, open-it commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
>                  <h3>137 200 €</h3>
Cet appartement est statique ? C'est normal ?

2017-07-11 15:46 UTC, open-it commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +{#            <div class="col l4 m4 s12">
Pas de code commenté

2017-07-11 15:47 UTC, open-it commented on src/MyOrleansBundle/Tests/Controller/TypeBienControllerTest.php
> +    /*
Qu'est ce ???!!!

2017-07-11 15:47 UTC, open-it requested changes
Y a du boulot !!!!

2017-07-11 17:59 UTC, Solcain commented on src/MyOrleansBundle/Tests/Controller/TypeBienControllerTest.php
> +    /*
pas la moindre idée !!!

2017-07-11 19:14 UTC, Solcain commented on src/MyOrleansBundle/Controller/front/PdfController.php
> +    public function pdfFlatAction($id, Flat $flat, SessionInterface $session, Request $request, CalculateurCaracteristiquesResidence $calculateur)
c'est réglé

2017-07-11 19:14 UTC, Solcain commented on src/MyOrleansBundle/Controller/front/PdfController.php
> +    public function pdfResidenceAction($id,Residence $residence, SessionInterface $session, CalculateurCaracteristiquesResidence $calculateur)
c'est réglé

2017-07-11 19:14 UTC, Solcain commented on src/MyOrleansBundle/Controller/front/ResidencesController.php
>          $media = $em->getRepository(Media::class)->find($id);
c'est réglé

2017-07-11 19:15 UTC, Solcain commented on src/MyOrleansBundle/Repository/FlatRepository.php
> +    public function searchById($id)
plus de methode

2017-07-11 19:16 UTC, Solcain commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
>                  <h3>137 200 €</h3>
oui je me suis occupé des residences en dynamique les apparts c'est après

2017-07-11 19:18 UTC, Solcain commented on src/MyOrleansBundle/Resources/views/appartement.html.twig
> +{#            <div class="col l4 m4 s12">
c'est réglé

2017-07-12 08:33 UTC, open-it requested changes
Ca ne va pas du tout. On regardera ca ensemble apres le checkpoint.

2017-07-12 13:05 UTC, open-it approved these changes
La PR est loin d'etre parfaite mais je l'accepte. Etant donné que tous le "dynamisme" est ici !!! Vous allez avoir des tests sur dev à faire !!!!

2017-07-12 13:19 UTC, merged