Bug fix#64
WildCodeSchool/orleans-0217-myorleans pull request #69
Opened 2017-07-11 19:51 UTC by WCSIsabelle

@sblondeau @open-it

2017-07-11 21:54 UTC, sblondeau requested changes

2017-07-11 21:54 UTC, sblondeau commented on src/MyOrleansBundle/Controller/admin/ResidenceController.php
> +                $media->setLien('default.jpg');
une question, le fichier upload normalement n'est pas versionné, or le default.jpg se trouve logiquement dans upload/default.jpg donc n'est pas versionné, donc non récupéré par d'autres et du coup... bug
l'idée serait de déversionner le dossier upload SAUF default.jpg

2017-07-11 21:54 UTC, sblondeau commented on src/MyOrleansBundle/Resources/views/index.html.twig
> +                                {% if residenceTwoFav is not empty %}
nom de variable residenceTwoFav pas clair, et variables suivantes non plus, à renommer si possible

2017-07-12 08:20 UTC, open-it approved these changes

2017-07-12 08:20 UTC, merged